POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Airbnb JavaScript Style Guide",
	"author": "Airbnb",
	"url": "https://github.com/airbnb/javascript",
	"likes": 148000
}

###

GET http://localhost:3001/api/blogs