POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Tittle",
	"author": "tester",
	"url": "sillylix.com",
	"likes": 20
}

###

GET http://localhost:3001/api/blogs