### get info
GET http://localhost:3001/info

### get all data
GET http://localhost:3001/api/persons

### get one data from specific id
GET  http://localhost:3001/api/persons/4

### get one data from specific id
DELETE http://localhost:3001/api/persons/4

### post data

POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "34125"
} 